/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xerxes54
 */
public class purchase extends javax.swing.JFrame {

    /**
     * Creates new form purchase
     */
    public purchase() {
        initComponents();
         fillTable();
    }

    
     public Connection MySqlConnection() {
        Connection conn=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/POS", "root", "xerxes54");
            JOptionPane.showMessageDialog(null, "Connection successful");
            return conn;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection failed");
            return null;
        }
    }
     
       public ArrayList<inventorybin> retrieveData(){
    ArrayList<inventorybin> al;
        al = new ArrayList<>();
    
    try{
    Connection conn = MySqlConnection();
    String qry="select * from purchase";
    Statement xer = conn.createStatement();
    ResultSet xe = xer.executeQuery(qry);
    inventorybin inventor = null;
    while (xe.next())
         inventor= new inventorybin(xe.getInt(1),xe.getString(2),xe.getInt(3),xe.getFloat(4),xe.getString(5),xe.getString(6));
    al.add(inventor);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Data Retrieval failure..."+e);
    }
    return al;
}

public void fillTable(){
    ArrayList<inventorybin>al;
        al = retrieveData();
    DefaultTableModel model = (DefaultTableModel)tble.getModel();
  
    Object[] row=new Object[6];
    for(int i=0;i<al.size();i++){
        row[0]=al.get(i).getId();
        row[1]=al.get(i).getName();
        row[2]=al.get(i).getQuantity();
        row[3]=al.get(i).getPrice();
        row[4]=al.get(i).getDate();
        row[5]=al.get(i).getUnit();
        
        model.addRow(row);
    }
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bla1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bla2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        bla4 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bla5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("           XERXES POS");

        jLabel2.setText("ID");

        jLabel3.setText("NAME");

        bla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bla1ActionPerformed(evt);
            }
        });

        jLabel4.setText("QUANTITY");

        jLabel5.setText("DATE");

        d.setDateFormatString("dd-MM-yyyy");

        jLabel6.setText("UNIT");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel7.setText("  PRICE");

        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Date", "Unit"
            }
        ));
        jScrollPane1.setViewportView(tble);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bla5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bla2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bla1)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bla4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bla1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bla4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bla2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bla5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bla1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(bla1.getText()!=null&&bla.getText()!=null&&!bla2.getText().equals("")&&!bla4.getText().equals("")&&!bla5.getText().equals(""))//&&male.isSelected()!=false
        // ||female.isSelected()!=false||other.isSelected()!=false)
        {
            try{

                Connection conn = MySqlConnection();
                String query = "INSERT INTO purchase(purch_Id,name,quantity,price,date,pur_unit)"+"VALUES(?,?,?,?,?,?)";
                PreparedStatement xer =conn.prepareStatement(query);

                xer.setInt(1,Integer.parseInt(bla.getText()));
                xer.setString(2,bla1.getText());
                xer.setInt(3,Integer.parseInt(bla2.getText()));
                xer.setFloat(4,Float.parseFloat(bla5.getText()));
                //xer.setString(3,bla2.getText());
                //xer.setString(4,bla5.getText());

                SimpleDateFormat xe = new SimpleDateFormat("dd-MM-yyyy");
                String x=xe.format(d.getDate());
                xer.setString(5, x);

                xer.setString(6,bla4.getText());

                //xer.setInt(6,Integer.parseInt(xer6.getText()));

                int a= xer.executeUpdate();

                if(a>=1){
                    JOptionPane.showMessageDialog(null,"record added succesfully..");
                    fillTable();
                }else
                JOptionPane.showMessageDialog(null,"Failed to add record..");

                
            }catch(SQLException | NumberFormatException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Failed to add record.."+e);
            }}else
            JOptionPane.showMessageDialog(null,"insert record to add");

    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(bla!=null||bla1!=null||bla2!=null||bla4!=null||bla5!=null||d!=null){
            String qry=null;
            PreparedStatement ps = null;
            Connection conn = MySqlConnection();

            if (!bla.equals("")){
                try{
                    qry="update purchase set name=?, quantity=?, price=?,date=?,pur_unit=? where purch_Id=?";
                    ps=conn.prepareStatement(qry);

                    ps.setInt(6,Integer.parseInt(bla.getText()));
                    ps.setString(1,bla1.getText());
                    ps.setInt(2,Integer.parseInt(bla2.getText()));
                    ps.setFloat(3,Float.parseFloat(bla5.getText()));

                    SimpleDateFormat xer = new SimpleDateFormat("dd-MM-yyyy");
                    String dob=xer.format(d.getDate());
                    ps.setString(4, dob);

                    ps.setString(5,bla4.getText());

                    //InputStream is = new FileInputStream(new File(photopath));
                    //ps.setBlob(5, is);

                    int xerxes=ps.executeUpdate();
                    if(xerxes>=1)
                    {
                        JOptionPane.showMessageDialog(null,"Successfully updated record...");
                        fillTable();
                    }
                    else
                    JOptionPane.showMessageDialog(null,"Error xer21...");

                    
                    // }catch (Exception e){

                    // if(xerxes>=1)
                    //{
                        //     JOptionPane.showMessageDialog(null,"Successfully updated student record...");}
                    // else
                    //  JOptionPane.showMessageDialog(null,"Error xer21...");

                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Field(s) missing!");
                }
                bla.setText("");
                bla1.setText("");
                bla2.setText("");
                bla4.setText("");
                bla5.setText("");

            } }else{
                JOptionPane.showMessageDialog(null," updation failed..");
            }

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(!bla.equals(""))
        {
            try{
                Connection conn = MySqlConnection();
                String sqlquery = "delete from purchase WHERE purch_Id=?";

                PreparedStatement  xer=conn.prepareStatement(sqlquery);

                xer.setInt(1,Integer.parseInt(bla.getText()));

                int a=xer.executeUpdate();
                if(a>=1){
                    JOptionPane.showMessageDialog(null," record deleted succesfully..");
                fillTable();
                }
                else
                JOptionPane.showMessageDialog(null,"Failed to delete record..");

                

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Failed to delete record..");
                
            }
        }else
        JOptionPane.showMessageDialog(null,"Input ID to delete record");

    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        PreparedStatement  xer;
        Connection conn;
        if(!bla1.getText().equals("")){
            try{
                conn=MySqlConnection();
                String sqlquery = "SELECT * FROM purchase WHERE name=?";

                xer=conn.prepareStatement(sqlquery);

                xer.setString(1,bla1.getText());

                ResultSet res= xer.executeQuery();

                while(res.next()){
                    String a = res.getString(1);
                    String b = res.getString(2);
                    String c = res.getString(3);
                    String d = res.getString(4);
                    String e = res.getString(6);

                    bla.setText(a);
                    bla1.setText(b);
                    bla2.setText(c);
                    bla5.setText(d);
                    bla4.setText(e);

                } }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Record not found..");
                }}else
                try{
                    conn=MySqlConnection();
                    String sqlquery = "SELECT * FROM inventory WHERE purch_Id=?";

                    xer=conn.prepareStatement(sqlquery);

                    xer.setInt(1,Integer.parseInt(bla.getText()));

                    ResultSet res= xer.executeQuery();

                    while(res.next()){
                        String a = res.getString(1);
                        String b = res.getString(2);
                        String c = res.getString(3);
                        String d = res.getString(4);
                        String e = res.getString(6);

                        bla.setText(a);
                        bla1.setText(b);
                        bla2.setText(c);
                        bla5.setText(d);
                        bla4.setText(e);

                    } }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Record not found..");}

    }//GEN-LAST:event_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(bla.getText()!=null||bla2.getText()!=null||bla1.getText()!=null||bla5.getText()!=null||bla4.getText()!=null){
            bla.setText("");
            bla1.setText("");
            bla2.setText("");
            bla4.setText("");
            bla5.setText("");
        }else
        JOptionPane.showMessageDialog(null,"No record to clear..");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField bla;
    private javax.swing.JTextField bla1;
    private javax.swing.JTextField bla2;
    private javax.swing.JTextField bla4;
    private javax.swing.JTextField bla5;
    private com.toedter.calendar.JDateChooser d;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTable tble;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
